application:
  subdomain: barkeep
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://barkeep:3000/
services:
  barkeep:
    # upstream: ghcr.io/nckslvrmn/bar_keep:v0.5.0
    image: ghcr.1ms.run/nckslvrmn/bar_keep:v0.5.0
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE={{ stable_secret "secrt-key-base" }}
      - ALLOWED_HOST={{.S.AppDomain}}
      - FORCE_SSL=false
    binds:
      - /lzcapp/var/data:/app/storage
